Import( "env", "dev", "mode")
localenv = env.Copy()

project = "problem"

#~ if we are on windows we need to tell gcc to bild a windows exe
#~ we need to set -mwindows as a compiler flag
import sys
if sys.platform == "win32":
    localenv.Tool( "mingw" )
    localenv[ "CCFLAGS" ] += [ "-mwindows" ]

localenv.Append (
        CCFLAGS = [
            "-W",
            "-Wconversion",
            "-Wshadow",
            "-Wcast-qual",
            "-Wwrite-strings",
            "-std=c++98"
        ]
    )
    
tgt = localenv.Program(project, dev.DevGetSourceFiles( ".", [ "*.cpp" ] ) )
localenv.Alias(project, tgt)
